const MIN_PASSWORD_LENGTH = 6;
const MAX_PASSWORD_LENGTH = 24;

const USER_ROLES = {
  ADMIN: 'admin',
  USER: 'user'
};

const DEFAULT_USER_ROLE = USER_ROLES.USER;

module.exports = {
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  USER_ROLES,
  DEFAULT_USER_ROLE
};